version: "3.8"

services:
  workspace:
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:0-20
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend:/workspace/frontend:cached
    working_dir: /workspace/frontend
    ports:
      - "5173:5173"
