version: "3.8"

services:
  workspace:
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:0-20
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend:/workspace/backend:cached
    working_dir: /workspace/backend
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
      - PORT=5001
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend:/workspace/frontend:cached
    working_dir: /workspace/frontend
    ports:
      - "5173:5173"

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
